### ISSUE TITLE
Memory Leak in ExperienceActivity

### ISSUE THREAD

**Issue by hudclark** [RoverPlatform/rover-android#154]
`ExperienceActivity.FetchExperienceTask` can leak its surrounding activity.

Steps to reproduce:
- Launch `ExperienceActivity`.
- Quickly click back, before ExperienceNetworkTask has finished. -- To make this easier to observe change the android emulator's network type to something very slow.
- `ExperienceActivity` is referenced by `FetchExperienceTask` and cannot be garbage collected.
- A tool like LeakCanary can make finding this leak easier.

**Comment by seanrucker** [comment]
@hudclark here is my understanding of the issue. Please correct me if you disagree with any of the following.

The background thread spawned by the FetchExperienceTask holds a reference to the task, which in-turn holds a reference to its outer class – the ExperienceActivity. When the ExperienceActivity is destroyed, the background thread maintains its reference to the task, which maintains its reference to the activity. This is the "leak" you are referring to. The activity can not be removed from memory due to the indirect reference the background thread has on it.

When the task eventually completes, the background thread's reference to the task is cleared and subsequently the task's reference to the activity is also cleared. At this time the Activity is available for garbage collection.

If you agree with the above, would it be fair to say this is not exactly a memory "leak" as the memory will eventually be reclaimed. I would agree this is an _inefficient_ use of memory, exacerbated by slow networking conditions, in which the Activity is remaining in-memory longer than necessary.

**Comment by hudclark** [comment]
@seanrucker That's also my understanding. I agree that perhaps this issue might be better labeled as an inefficient use of memory, rather than a leak. It is a 'leak' in that LeakCanary detects that the Activity is finished but it cannot be reclaimed by GC.

However, I do think this is an issue working fixing. A poor network connection or other network issues could cause the FetchExperienceTask take a long time to complete, and an Activity is an expensive object to hold in memory.

**Comment by seanrucker** [comment]
I agree it is worth fixing. I'll comment further on your PR.

I had not heard of Leak Canary before. I installed the module and tried to get it to report the leak but was unsuccessful. Any tips for me?

**Comment by hudclark** [comment]
Sure,

After adding leak canary and configuring it as per their readme: https://github.com/square/leakcanary, here are the steps I can do to reproduce it. Note that it will take leak canary upwards of a minute to actually show the notification saying there is a leak.

1) Ensure that the network request is not cached.
2) In Android emulator set Network Type to GPRS, and Signal strength to poor.
3) Open the ExperienceActivity and press the android system back button quickly, before the network request has completed.
4) Once LeakCanary has processed the 'leak' it should display a notification.
