### ISSUE TITLE
Create RoverFragment (and thicker/smarter RoverView, with a thinner RoverActivity)

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#372]
Android Fragments are enjoying a little bit of a renaissance.  We should have first class support for them, especially considering they appear to be the default use case with Jetpack Navigation.

- [ ] Create RoverFragment, embedding RoverView;
- [ ] Test it with Jetpack Navigation;
- [ ] Add a new section to the Deep & Universal Links documentation which describes how to use Jetpack Navigation (with links) in lieu of the manual if-statement example routing;
- [ ] Consider refactoring common functionality in RoverActivity and the new RoverFragment into RoverView. This will also have the effect of making RoverView easier to use (right now you have to manually construct and bind a RoverViewModel to RoverView, etc. etc.).
- [ ] Make the new RoverView public API (and thus suitable for use in View-only Android apps).

Note: please avoid changing RoverActivity public API, since that has already gone public in Beta 1.  However changing public API of RoverView is OK because that is not likely to be used yet.

RoverActivity should continue to embed RoverView directly, but should hopefully do little else.

**Comment by orospakr** [comment]
This does not change existing public API, so while it isn't high priority, getting it into final release of 3.0.0 would certainly be nice.

**Comment by samwoodall** [comment]
This is slightly more involved than we envisioned.

A few things to think about:
- How to handle navigation between the different experience screens. This isn't a problem with our RoverActivity but with a fragment, the host activity needs to control navigation between screens so needs to override `onBackPressed`
- How the user can control external navigation events such as the exit navigation event. Should the fragment pop itself off the backstack or should the host activity control what happens based upon the navigation events. 
- How the `Toolbar` interaction works, should the fragment set the toolbar of the host activity? Or is there a way to avoid this? What happens when the fragment is no longer attached to the host activity in terms of the toolbar and status bar?

### Actions 
- [ ] Make sure Rover is compatible with the Navigation Component
- [ ] Provide a RoverFragment that solves the above issues
